name: enhanced_platform_menu
description: "An enhanced drop-in replacement for Flutterâ€™s Platform Menu API
  with support for checked items and icons on macOS and iPadOS."
version: 0.1.2
homepage: https://github.com/tstumpSC/enhanced_platform_menu
issue_tracker: https://github.com/tstumpSC/enhanced_platform_menu/issues
repository: https://github.com/tstumpSC/enhanced_platform_menu

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: EnhancedPlatformMenuPlugin
      macos:
        pluginClass: EnhancedPlatformMenuPlugin

topics:
  - menus
  - macos
  - ipados
  - desktop
  - shortcuts